name: On PR

on:
  pull_request:
    branches: [main]

env:
  BASE_DOCKERFILE: Dockerfile.cuda-11.1

jobs:
  docker-build-test-11-4-2:
    runs-on: [self-hosted, linux, x64, turbo]
    env:
      BASE_DOCKERFILE: cuda-11.4.2.Dockerfile
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Build Test - All Architecture
        run: |
          docker build --build-arg CUDA_ARCH=86 --pull -t dev/build:test-86 -f $BASE_DOCKERFILE .
  docker-build-test-11-1:
    runs-on: [self-hosted, linux, x64, turbo]
    env:
      BASE_DOCKERFILE: cuda-11.1.1.Dockerfile
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Build Test - All Architecture
        run: |
          docker build --build-arg CUDA_ARCH=60 --pull -t dev/build:test-60 -f $BASE_DOCKERFILE .
  docker-build-test-10-2:
    runs-on: [self-hosted, linux, x64, turbo]
    env:
      BASE_DOCKERFILE: cuda-10.2.89.Dockerfile
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Build Test - All Architecture
        run: |
          docker build --build-arg CUDA_ARCH=35 --pull -t dev/build:test-35 -f $BASE_DOCKERFILE .
