name: On PR Merge - CUDA 11.1

on:
  pull_request:
    types: [closed]

env:
  BASE_DOCKERFILE: cuda-11.1.Dockerfile
  BASE_IMAGE_NAME: pinteraktif/cuda-opencv-ffmpeg:11.1

jobs:
  arch-86:
    if: github.event.pull_request.merged == true
    runs-on: self-hosted
    env:
      CUDA_ARCH: 86
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Build & Push
        run: |
          # Login to Github docker registry
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

          # Compose proper Image ID
          IMAGE_TAG=ghcr.io/$BASE_IMAGE_NAME-$CUDA_ARCH

          # Change all uppercase to lowercase
          IMAGE_TAG=$(echo $IMAGE_TAG | tr '[A-Z]' '[a-z]')

          echo IMAGE_TAG=$IMAGE_TAG

          # Build then push
          docker build --build-arg CUDA_ARCH=$CUDA_ARCH --pull -t $IMAGE_TAG -f $BASE_DOCKERFILE .
          docker push $IMAGE_TAG
  arch-80:
    if: github.event.pull_request.merged == true
    runs-on: self-hosted
    env:
      CUDA_ARCH: 80
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Build & Push
        run: |
          # Login to Github docker registry
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

          # Compose proper Image ID
          IMAGE_TAG=ghcr.io/$BASE_IMAGE_NAME-$CUDA_ARCH

          # Change all uppercase to lowercase
          IMAGE_TAG=$(echo $IMAGE_TAG | tr '[A-Z]' '[a-z]')

          echo IMAGE_TAG=$IMAGE_TAG

          # Build then push
          docker build --build-arg CUDA_ARCH=$CUDA_ARCH --pull -t $IMAGE_TAG -f $BASE_DOCKERFILE .
          docker push $IMAGE_TAG
  arch-75:
    if: github.event.pull_request.merged == true
    runs-on: self-hosted
    env:
      CUDA_ARCH: 75
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Build & Push
        run: |
          # Login to Github docker registry
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

          # Compose proper Image ID
          IMAGE_TAG=ghcr.io/$BASE_IMAGE_NAME-$CUDA_ARCH

          # Change all uppercase to lowercase
          IMAGE_TAG=$(echo $IMAGE_TAG | tr '[A-Z]' '[a-z]')

          echo IMAGE_TAG=$IMAGE_TAG

          # Build then push
          docker build --build-arg CUDA_ARCH=$CUDA_ARCH --pull -t $IMAGE_TAG -f $BASE_DOCKERFILE .
          docker push $IMAGE_TAG
  arch-70:
    if: github.event.pull_request.merged == true
    runs-on: self-hosted
    env:
      CUDA_ARCH: 70
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Build & Push
        run: |
          # Login to Github docker registry
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

          # Compose proper Image ID
          IMAGE_TAG=ghcr.io/$BASE_IMAGE_NAME-$CUDA_ARCH

          # Change all uppercase to lowercase
          IMAGE_TAG=$(echo $IMAGE_TAG | tr '[A-Z]' '[a-z]')

          echo IMAGE_TAG=$IMAGE_TAG

          # Build then push
          docker build --build-arg CUDA_ARCH=$CUDA_ARCH --pull -t $IMAGE_TAG -f $BASE_DOCKERFILE .
          docker push $IMAGE_TAG
  arch-61:
    if: github.event.pull_request.merged == true
    runs-on: self-hosted
    env:
      CUDA_ARCH: 61
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Build & Push
        run: |
          # Login to Github docker registry
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

          # Compose proper Image ID
          IMAGE_TAG=ghcr.io/$BASE_IMAGE_NAME-$CUDA_ARCH

          # Change all uppercase to lowercase
          IMAGE_TAG=$(echo $IMAGE_TAG | tr '[A-Z]' '[a-z]')

          echo IMAGE_TAG=$IMAGE_TAG

          # Build then push
          docker build --build-arg CUDA_ARCH=$CUDA_ARCH --pull -t $IMAGE_TAG -f $BASE_DOCKERFILE .
          docker push $IMAGE_TAG
  arch-60:
    if: github.event.pull_request.merged == true
    runs-on: self-hosted
    env:
      CUDA_ARCH: 60
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Build & Push
        run: |
          # Login to Github docker registry
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

          # Compose proper Image ID
          IMAGE_TAG=ghcr.io/$BASE_IMAGE_NAME-$CUDA_ARCH

          # Change all uppercase to lowercase
          IMAGE_TAG=$(echo $IMAGE_TAG | tr '[A-Z]' '[a-z]')

          echo IMAGE_TAG=$IMAGE_TAG

          # Build then push
          docker build --build-arg CUDA_ARCH=$CUDA_ARCH --pull -t $IMAGE_TAG -f $BASE_DOCKERFILE .
          docker push $IMAGE_TAG
  arch-52:
    if: github.event.pull_request.merged == true
    runs-on: self-hosted
    env:
      CUDA_ARCH: 52
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Build & Push
        run: |
          # Login to Github docker registry
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

          # Compose proper Image ID
          IMAGE_TAG=ghcr.io/$BASE_IMAGE_NAME-$CUDA_ARCH

          # Change all uppercase to lowercase
          IMAGE_TAG=$(echo $IMAGE_TAG | tr '[A-Z]' '[a-z]')

          echo IMAGE_TAG=$IMAGE_TAG

          # Build then push
          docker build --build-arg CUDA_ARCH=$CUDA_ARCH --pull -t $IMAGE_TAG -f $BASE_DOCKERFILE .
          docker push $IMAGE_TAG
